#### Data Transformation means changing data into a format that a machine learning model can understand and learn from.
##### Converting raw data into clean and usable data.

  Raw Data
    ->
  Handle missing values
     ->
 Scale numerical features 
     ->
 Split into train & test
     ->
 Model training

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load the dataset from CSV file
data = pd.read_csv('/DataScinceExlr/Assignments/9. Data Transformation/adult_with_headers.csv')

In [3]:
data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [5]:
data.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

#### 1. Handling Missing Values

In [6]:
data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [7]:
# Check unique values in the 'occupation' column
data['occupation'].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

- The value '?' represents a missing or unknown value.

 ##### It means:
The person’s occupation was not recorded
Or the data was not available at the time of collection

In [10]:
# Check unique values in each categorical column - Detect invalid placeholders like ' ?'
# This helps identify placeholders like '?', 'NA', 'NULL', etc.
for col in data.select_dtypes(include="object").columns:
    print(col)
    print(data[col].unique())
    print("-" * 40)

workclass
[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
----------------------------------------
education
[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']
----------------------------------------
marital_status
[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']
----------------------------------------
occupation
[' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transport-moving'
 ' Farming-fishing' ' Machine-op-inspct' ' Tech-support' ' ?'
 ' Protective-serv' ' Armed-Forces' ' Priv-house-serv']
----------------------------------------
relationship
[' Not-in-family' ' Husband' ' Wife' ' Own-child' ' Unmarried'
 ' Other-relative']
----------------------------------------
race
[' White' ' Black' ' Asian-Pac-Islander' ' Amer-Indian-Eskimo' ' Other']
----------------------------------------
sex
[' Male' ' Female']
----------------------------------------
native_country
[' United-States' ' Cuba' ' Jamaica' ' India' ' ?' ' Mexico' ' South'
 ' Puerto-Rico' ' Honduras' ' England' ' Canada' ' Germany' ' Iran'
 ' Philippines' ' Italy' ' Poland' ' Columbia' ' Cambodia' ' Thailand'
 ' Ecuador' ' Laos' ' Taiwan' ' Haiti' ' Portugal' ' Dominican-Republic'
 ' El-Salvador' ' France' ' Guatemala' ' China' ' Japan' ' Yugoslavia'
 ' Peru' ' Outlying-US(Guam-USVI-etc)' ' Scotland' ' Trinadad&Tobago'
 ' Greece' ' Nicaragua' ' Vietnam' ' Hong' ' Ireland' ' Hungary'
 ' Holand-Netherlands']
----------------------------------------
income
[' <=50K' ' >50K']
----------------------------------------

#### The unique values of categorical columns were analyzed to identify valid categories and detect missing placeholders such as '?'. Columns containing placeholders require cleaning before encoding and model training. 
#### namely:  'workclass', 'occupation' and 'native_country'.

In [15]:
# Select categorical columns
cat_cols = data.select_dtypes(include='object').columns

# Remove leading/trailing spaces
for col in cat_cols:
    data[col] = data[col].str.strip()

In [16]:
# Replace '?' with NaN
data.replace('?', np.nan, inplace=True)

In [18]:
# Verify 
for col in data.select_dtypes(include="object").columns:
    print(col)
    print(data[col].unique())
    print("-" * 40)

workclass
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' nan
 'Self-emp-inc' 'Without-pay' 'Never-worked']
----------------------------------------
education
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
----------------------------------------
marital_status
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
----------------------------------------
occupation
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' nan
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']
----------------------------------------
relationship
['Not-in-family' 'Husband' 'Wife' 'Own-child' 'Unmarried' 'Other-relative']
----------------------------------------
race
['White' 'Black' 'Asian-Pac-Islander' 'Amer-Indian-Eskimo' 'Other']
----------------------------------------
sex
['Male' 'Female']
----------------------------------------
native_country
['United-States' 'Cuba' 'Jamaica' 'India' nan 'Mexico' 'South'
 'Puerto-Rico' 'Honduras' 'England' 'Canada' 'Germany' 'Iran'
 'Philippines' 'Italy' 'Poland' 'Columbia' 'Cambodia' 'Thailand' 'Ecuador'
 'Laos' 'Taiwan' 'Haiti' 'Portugal' 'Dominican-Republic' 'El-Salvador'
 'France' 'Guatemala' 'China' 'Japan' 'Yugoslavia' 'Peru'
 'Outlying-US(Guam-USVI-etc)' 'Scotland' 'Trinadad&Tobago' 'Greece'
 'Nicaragua' 'Vietnam' 'Hong' 'Ireland' 'Hungary' 'Holand-Netherlands']
----------------------------------------
income
['<=50K' '>50K']
----------------------------------------

In [19]:
# Check missing (null) values in each column
data.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [21]:
# Check numeric columns for zero value(Check Zero Counts)
num_features = data.select_dtypes(include=['int64', 'float64']).columns

for feature in num_features:
    zero_count = (data[feature] == 0).sum()
    print(f"{feature} has {zero_count} zero values")

age has 0 zero values
fnlwgt has 0 zero values
education_num has 0 zero values
capital_gain has 29849 zero values
capital_loss has 31042 zero values
hours_per_week has 0 zero values

In [22]:
# Replace zero values with median for numeric columns
numeric_columns = data.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_columns:
    if (data[col] == 0).any():
        median_val = data.loc[data[col] != 0, col].median()
        data.loc[data[col] == 0, col] = median_val

In [25]:
# Check categorical columns and replce  with median value
cat_col = data.select_dtypes(include="object").columns

In [26]:
# Replace missing categorical values with mode
data[cat_col] = data[cat_col].apply(lambda x: x.fillna(x.mode()[0]))

In [27]:
# Verify that there are no missing values in the dataset
data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

#### 1.Apply scaling techniques to numerical features

In [28]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [30]:
# Apply standard scaling to numerical features
scaler = StandardScaler()
data_scaled = data.copy()

In [32]:
# Apply standard scaling to numerical columns
num_col = data.select_dtypes(include=["int64", "float64"]).columns
data_scaled[num_col] = scaler.fit_transform(data_scaled[num_col])

In [33]:
# Feature scaling ensures that all features contribute equally to the model
# Standard scaling helps achieve faster convergence during optimization
# It is commonly used when features follow (or are close to) a normal distribution

In [34]:
# Applying Min-Max Scaling
mm_scaler = MinMaxScaler()
data_mm = data.copy()

In [35]:
# Applying Min-Max scaling to numerical columns
# This scales values between 0 and 1 using min and max of each feature
data_mm[num_col] = mm_scaler.fit_transform(data[num_col])

In [36]:
# Min-Max scaler is used when the data is NOT normally distributed
# It scales all values between 0 and 1

#### 2. Encoding Techniques:

In [37]:
# checking how many unique values in each categorical column
data[cat_col].nunique()

workclass          8
education         16
marital_status     7
occupation        14
relationship       6
race               5
sex                2
native_country    41
income             2
dtype: int64

- If number of categories ≤ 5  → One-Hot Encoding
- If number of categories > 5  → Label Encoding

In [38]:
# One-hot encoding for low-cardinality categorical columns (≤ 5 unique values)
low_cardinality_cols = [col for col in cat_col if data[col].nunique() <= 5]

data = pd.get_dummies(data, columns=low_cardinality_cols, drop_first=True)

In [39]:
from sklearn.preprocessing import LabelEncoder

# High-cardinality categorical columns
high_cardinality_cols = [col for col in cat_col if col not in low_cardinality_cols]

label_encoder = LabelEncoder()

for col in high_cardinality_cols:
    data[col] = label_encoder.fit_transform(data[col])

In [40]:
# verifying line of code
data.head(10)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,hours_per_week,native_country,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,income_>50K
0,39,6,77516,9,13,4,0,1,2174,1887,40,38,False,False,False,True,True,False
1,50,5,83311,9,13,2,3,0,7298,1887,13,38,False,False,False,True,True,False
2,38,3,215646,11,9,0,5,1,7298,1887,40,38,False,False,False,True,True,False
3,53,3,234721,1,7,2,5,0,7298,1887,40,38,False,True,False,False,True,False
4,28,3,338409,9,13,2,9,5,7298,1887,40,4,False,True,False,False,False,False
5,37,3,284582,12,14,2,3,5,7298,1887,40,38,False,False,False,True,False,False
6,49,3,160187,6,5,3,7,1,7298,1887,16,22,False,True,False,False,False,False
7,52,5,209642,11,9,2,3,0,7298,1887,45,38,False,False,False,True,True,True
8,31,3,45781,12,14,4,9,1,14084,1887,50,38,False,False,False,True,False,True
9,42,3,159449,9,13,2,3,0,5178,1887,40,38,False,False,False,True,True,True

#### 3. Feature Engineering:

In [41]:
# Create a new feature: Net Capital Gain
data["capital_net"] = data["capital_gain"] - data["capital_loss"]

In [42]:
# Create a new feature: Work Intensity Score
data["work_intensity"] = data["hours_per_week"] * data["education_num"]

In [43]:
# Compare skewness of all numerical features
num_cols = data.select_dtypes(include=["int64", "float64"]).columns
data[num_cols].skew().sort_values(ascending=False)

capital_gain      13.108170
capital_net       13.105168
fnlwgt             1.446980
capital_loss       1.165261
work_intensity     0.697997
age                0.558743
hours_per_week     0.227643
education_num     -0.311676
dtype: float64

In [44]:
# Capital gain shows extreme positive skewness with a long right tail
# Apply log transformation to reduce skewness
data["capital_gain_log"] = np.log1p(data["capital_gain"])

In [45]:
# Final ready data for model building
data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,native_country,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,income_>50K,capital_net,work_intensity,capital_gain_log
0,39,6,77516,9,13,4,0,1,2174,1887,...,38,False,False,False,True,True,False,287,520,7.684784
1,50,5,83311,9,13,2,3,0,7298,1887,...,38,False,False,False,True,True,False,5411,169,8.895493
2,38,3,215646,11,9,0,5,1,7298,1887,...,38,False,False,False,True,True,False,5411,360,8.895493
3,53,3,234721,1,7,2,5,0,7298,1887,...,38,False,True,False,False,True,False,5411,280,8.895493
4,28,3,338409,9,13,2,9,5,7298,1887,...,4,False,True,False,False,False,False,5411,520,8.895493